apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker-conversion # Replace with your microservice name
  labels:
    app: spring-docker-conversion
spec:
  replicas: 1  # Adjust for desired number of replicas
  selector:
    matchLabels:
      app: spring-docker-conversion
  template:
    metadata:
      labels:
        app: spring-docker-conversion
    spec:
      containers:
      - name: spring-docker-conversion
        image: spring-docker-conversion:latest  # Replace with your Docker image details
        # Resource requests and limits (adjust based on your application's needs)
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://spring-docker-serviceregistry:8761/eureka/
        - name: SPRING_APPLICATION_NAME
          value: Conversion
        - name: SERVER_PORT
          value: "8080"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Optional: Port configuration (modify if your microservice uses a different port)
        ports:
        - containerPort: 8080 # Adjust if needed
---
apiVersion: v1
kind: Service
metadata:
  name: spring-docker-conversion # Replace with your microservice name
spec:
  selector:
    app: spring-docker-conversion
  ports:
  - protocol: TCP
    port: 8080  # External port for communication (adjust if needed)
    targetPort: 8080  # Internal container port
  type: LoadBalancer